  
version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: $USER
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: $USER
      timeout: 60
