version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  AfterInstall:
    - location: scripts/test-app.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: scripts/test-react.sh
      runas: ubuntu
      timeout: 60
