version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
permissions:
  - object: scripts/
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 655
    type:
      - file  
hooks:
  AfterInstall:
    - location: scripts/runservice.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: scripts/startserver.sh
      runas: ubuntu
      timeout: 60

